name: tdm_user_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  custom_refresh_indicator: ^3.0.0    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/  

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf  
    - family: Asus Rog
      fonts:
        - asset: fonts/rog.ttf
